services:
  telegram_bot:
    build:
      context: .
      dockerfile: packages/telegram_bot/Dockerfile
      ssh:
        - default
    container_name: telegram-bot
    environment:
      JOB_AGENT_BOT_TOKEN: ${JOB_AGENT_BOT_TOKEN}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672${RABBITMQ_VHOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OLLAMA_BASE_URL: http://ollama:11434
      LANGSMITH_TRACING_V2: ${LANGSMITH_TRACING_V2}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
    networks:
      - job-agent-network
    restart: unless-stopped

  ollama-puller:
    image: ollama/ollama:0.5.4
    container_name: job-agent-ollama-puller
    entrypoint: /bin/sh
    command: "-c 'sleep 5; ollama pull phi3:mini'"
    environment:
      - OLLAMA_HOST=ollama:11434
    networks:
      - job-agent-network
    restart: "no"

networks:
  job-agent-network:
    external: true
    name: job-agent-network
