[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "job-agent-backend"
version = "0.1.0"
description = "Job Agent backend - multiagent system for job processing and filtering"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "langgraph>=1.0.2",
    "langchain>=1.0.3",
    "langchain-openai>=1.0.1",
    "langsmith>=0.4.39",
    "pydantic>=2.0.0",
    "pypdf>=5.1.0",
    "job-scrapper-contracts @ git+https://github.com/job-agent/job-scrapper-contracts.git@v0.1.1",
    "scrapper-service @ git+ssh://git@github.com/job-agent/scrappers.git@v0.1.4#subdirectory=packages/scrapper-service",
#    Mock service
#    "scrapper-service @ git+ssh://git@github.com/job-agent/scrappers-mock.git@v0.1.1#subdirectory=packages/scrapper-service",
    "jobs-repository>=0.1.0",
    "cvs-repository>=0.1.0",
    "job-agent-platform-contracts>=0.1.0",
    "dependency-injector>=4.45.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.2",
    "black>=25.9.0",
    "ruff>=0.14.3",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.ruff]
line-length = 100
target-version = "py39"
